sudo: required
dist: trusty

language: python

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"

    - os: osx
      language: generic
      env:
        - OSXENV=3.6.0
    - os: osx
      language: generic
      env:
        - OSXENV=2.7.14

install:
  - export PYVER=${TRAVIS_PYTHON_VERSION:0:1}
  - if [ $PYVER = 3 ]; then
      export PYCMD=python3;
      export PIPCMD=pip3;
    else
      export PYCMD=python;
      export PIPCMD=pip;
    fi;

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install pyenv;
      brew upgrade pyenv;
      brew install pyenv-virtualenv;
      eval "$(pyenv init -)";
      eval "$(pyenv virtualenv-init -)";
      pyenv install $OSXENV;
      pyenv virtualenv $OSXENV venv;
      pyenv activate venv;
      which python;
      python --version;
      which pip;
      export PYCMD=python;
      export PIPCMD=pip;
    fi;

  - $PIPCMD install odml 'nixio>=1.5.0b1'

script:
  - which $PYCMD
  - $PYCMD setup.py build
  - $PYCMD setup.py test
