version: 1.4.{build}

image: Visual Studio 2017

branches:
  only:
    - master
    - dev

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYVER: 3
      BITS: 64
    - PYTHON: "C:\\Python37-x64"
      PYVER: 3
      BITS: 64
    - PYTHON: "C:\\Python38-x64"
      PYVER: 3
      BITS: 64

init:
  - "ECHO %PYTHON% %vcvars% (%bits%)"
  - ps: $env:PATH = "$env:PYTHON;$env:PATH;"
  - python -c "import sys;print('Python version is {}'.format(sys.version))"

build: false

# setuptools and wheels are required for the 64 bit hdf5 installation
install:
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install odml nixio pytest

test_script:
  - python --version
  - python setup.py install
  - python -m pytest -v
