environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYVER: "2.7"
    - PYTHON: "C:\\Python35"
      PYVER: "3.5"
    - PYTHON: "C:\\Python36"
      PYVER: "3.6"
    - PYTHON: "C:\\Python27-x64"
      PYVER: "2.7"
    - PYTHON: "C:\\Python35-x64"
      PYVER: "3.5"
    - PYTHON: "C:\\Python36-x64"
      PYVER: "3.6"

build: false

install:
  - python -m pip install nixio odml

test_script:
  - python --version
  - python setup.py test
